# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("linguist", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        )
    ]
